if [ -f ~/.bashrc ]; then
	source ~/.bashrc
fi

if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export PATH=/usr/local/sbin:$PATH
export PGDATA=/usr/local/var/postgres
export PYTHONDONTWRITEBYTECODE=True
export CLICOLOR=1
export GREP_OPTIONS='--color=auto'

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Projects
source /usr/local/bin/virtualenvwrapper.sh

export PS1='\@ \w$ '

alias encrypt="openssl des3 -in $1 -out $2"
alias decrypt="openssl des3 -d -in $1 -out $2"
alias ll="ls -lah"
alias git=hub

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

if [ -f `brew --prefix`/etc/bash_completion ]; then
. `brew --prefix`/etc/bash_completion
fi

source ~/.profile
